apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: default-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: chenshaowen
  namespace: default
spec:
  gateways:
    - default/default-gateway
  hosts:
    - 'istio.chenshaowen.com'
  http:
    - match:
        - uri:
            exact: /
      route:
        - destination:
            host: blog.default.svc.cluster.local
            port:
              number: 80