FROM spark:3.5.1-python3
RUN wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.769/aws-java-sdk-bundle-1.12.769.jar -O /opt/spark/jars/aws-java-sdk-bundle-1.12.769.jar
RUN wget https://repo1.maven.org/maven2/software/amazon/awssdk/aws-sdk-java/2.27.17/aws-sdk-java-2.27.17.jar -O /opt/spark/jars/aws-sdk-java-2.27.17.jar
RUN wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar -O /opt/spark/jars/hadoop-aws-3.3.4.jar
