apiVersion: v1
kind: Namespace
metadata:
  name: spark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-iceberg
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-iceberg
  template:
    metadata:
      labels:
        app: spark-iceberg
    spec:
      containers:
        - name: spark-iceberg
          imagePullPolicy: Always
          image: shaowenchen/spark-iceberg:3.5.1_1.5.0-s3
          ports:
            - containerPort: 8888
            - containerPort: 8080
            - containerPort: 10000
            - containerPort: 10001
          env:
            - name: BUCKET
              value: "xxx"
            - name: ACCESS_KEY
              value: "xxx"
            - name: SECRET_KEY
              value: "xxx"
            - name: ENDPOINT
              value: "ks3-cn-beijing-internal.ksyuncs.com"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-iceberg
  namespace: spark
spec:
  selector:
    app: spark-iceberg
  ports:
    - name: http-8888
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: tcp-10000
      protocol: TCP
      port: 10000
      targetPort: 10000
    - name: tcp-10001
      protocol: TCP
      port: 10001
      targetPort: 10001
