apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-proxy
  namespace: kube-system
  labels:
    app: registry-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-proxy
  template:
    metadata:
      labels:
        app: registry-proxy
    spec:
      hostNetwork: true
      containers:
      - name: registry
        image: registry.cn-beijing.aliyuncs.com/opshub/registry:2
        ports:
        - containerPort: 443
          name: registry
        env:
        - name: REGISTRY_STORAGE
          valueFrom:
            configMapKeyRef:
              name: registry-config
              key: REGISTRY_STORAGE
        - name: REGISTRY_STORAGE_S3_ACCESSKEY
          valueFrom:
            configMapKeyRef:
              name: registry-config
              key: REGISTRY_STORAGE_S3_ACCESSKEY
        - name: REGISTRY_STORAGE_S3_SECRETKEY
          valueFrom:
            configMapKeyRef:
              name: registry-config
              key: REGISTRY_STORAGE_S3_SECRETKEY
        - name: REGISTRY_STORAGE_S3_REGION
          valueFrom:
            configMapKeyRef:
              name: registry-config
              key: REGISTRY_STORAGE_S3_REGION
        - name: REGISTRY_STORAGE_S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: registry-config
              key: REGISTRY_STORAGE_S3_BUCKET
        - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
          valueFrom:
            configMapKeyRef:
              name: registry-config
              key: REGISTRY_STORAGE_S3_REGIONENDPOINT
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
        volumeMounts:
        - name: config
          mountPath: /etc/docker/registry/config.yml
          subPath: config.yml
        - name: config
          mountPath: /auth/htpasswd
          subPath: htpasswd
        - name: config
          mountPath: /certs/tls.crt
          subPath: tls.crt
        - name: config
          mountPath: /certs/tls.key
          subPath: tls.key
      volumes:
      - name: config
        configMap:
          name: registry-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: kube-system
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /registry
    http:
      addr: :443
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    proxy:
      remoteurl: https://your-source-registry.com
      username: ""
      password: ""
  REGISTRY_STORAGE: s3
  REGISTRY_STORAGE_S3_ACCESSKEY: ""
  REGISTRY_STORAGE_S3_SECRETKEY: ""
  REGISTRY_STORAGE_S3_REGION: ""
  REGISTRY_STORAGE_S3_BUCKET: ""
  REGISTRY_STORAGE_S3_REGIONENDPOINT: ""
  htpasswd: ""
  tls.crt: |
    ""
  tls.key: |
    ""
---
