{
 "title": "Kindling Network Detail",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values(kindling_topology_request_total, src_workload_name)"
    }
   },
   {
    "name": "destination",
    "label": "Destination",
    "query": {
     "query": "label_values(kindling_topology_request_total, dst_workload_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Retransmit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kindling_tcp_retransmit_total{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"}[$__interval]))",
     "legendFormat": "Retransmit"
    }
   ]
  },
  {
   "title": "Packet Lost",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kindling_tcp_packet_loss_total{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"}[$__interval]))",
     "legendFormat": "Package Lost"
    }
   ]
  },
  {
   "title": "SRTT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (src_workload_name, dst_workload_name) (kindling_tcp_srtt_microseconds{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"}))",
     "legendFormat": "{{src_workload_name}}-{{dst_workload_name}}"
    }
   ]
  },
  {
   "title": "Network Volume",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kindling_topology_request_request_bytes_total{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"}[$__interval]))",
     "legendFormat": "Sent Volume"
    },
    {
     "expr": "sum(increase(kindling_topology_request_response_bytes_total{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"}[$__interval]))",
     "legendFormat": "Received Volume"
    }
   ]
  },
  {
   "title": "Connections Detail",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (src_workload_name, dst_workload_name) (kindling_trace_request_duration_nanoseconds{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"})"
    },
    {
     "expr": "sum by (src_workload_name, dst_workload_name) (increase(kindling_tcp_retransmit_total{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"}[$__interval])) and sum by (src_workload_name, dst_workload_name) (kindling_trace_request_duration_nanoseconds{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"})"
    },
    {
     "expr": "sum by (src_workload_name, dst_workload_name) (increase(kindling_tcp_packet_loss_total{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"}[$__interval])) and sum by (src_workload_name, dst_workload_name) (kindling_trace_request_duration_nanoseconds{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"})"
    },
    {
     "expr": "sum by (src_workload_name, dst_workload_name) (increase(kindling_topology_request_request_bytes_total{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"}[$__interval])) and sum by (src_workload_name, dst_workload_name) (kindling_trace_request_duration_nanoseconds{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"})"
    },
    {
     "expr": "sum by (src_workload_name, dst_workload_name) (increase(kindling_topology_request_response_bytes_total{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"}[$__interval])) and sum by (src_workload_name, dst_workload_name) (kindling_trace_request_duration_nanoseconds{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"})"
    },
    {
     "expr": "sum by (src_workload_name, dst_workload_name) (kindling_tcp_srtt_microseconds{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"}) and sum by (src_workload_name, dst_workload_name) (kindling_trace_request_duration_nanoseconds{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"})"
    }
   ]
  },
  {
   "title": "Retransmit Detail",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "increase(kindling_tcp_retransmit_total{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"}[$__range])"
    }
   ]
  },
  {
   "title": "Package Lost Detail",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "increase(kindling_tcp_packet_loss_total{src_workload_name=~\"$source\", dst_workload_name=~\"$destination\"}[$__range])"
    }
   ]
  }
 ]
}