{
 "title": "Kindling WorkLoad Detail",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kindling_entity_request_total, namespace)"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(kindling_entity_request_total{namespace =\"$namespace\"} , workload_name)"
    }
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": {
     "query": "label_values(kindling_entity_request_total{namespace =\"$namespace\",workload_name=\"$workload\",protocol!=\"NOSUPPORT\"}, protocol)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Request Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kindling_entity_request_total{namespace=\"$namespace\",workload_name=\"$workload\", protocol=\"$protocol\"}[$__interval]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace, workload_name) (increase(kindling_entity_request_duration_nanoseconds_total{namespace=\"$namespace\", workload_name=\"$workload\", protocol=\"$protocol\"}[$__interval])) / sum by(namespace, workload_name) \n (increase(kindling_entity_request_total{namespace=\"$namespace\", workload_name=\"$workload\", protocol=\"$protocol\"}[$__interval]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Erroneous Calls rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (increase(kindling_entity_request_total{namespace=\"$namespace\",workload_name=\"$workload\",protocol=\"$protocol\",response_content=~\"4..|5..|1|2|3\"}[$__interval])) / sum (increase(kindling_entity_request_total{namespace=\"$namespace\",workload_name=\"$workload\",protocol=\"$protocol\"}[$__interval])) * 100",
     "legendFormat": "Err rate"
    }
   ]
  },
  {
   "title": "Request Counts Top10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(increase(kindling_entity_request_total{namespace=\"$namespace\",workload_name=\"$workload\",protocol=\"$protocol\"}[$__interval])) by(request_content))",
     "legendFormat": "{{request_content}}"
    }
   ]
  },
  {
   "title": "Latency Top10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(request_content) (increase(kindling_entity_request_duration_nanoseconds_total{namespace=\"$namespace\", workload_name=\"$workload\",protocol=\"$protocol\"}[$__interval])) / sum by(request_content)  (increase(kindling_entity_request_total{namespace=\"$namespace\", workload_name=\"$workload\",protocol=\"$protocol\"}[$__interval]))) ",
     "legendFormat": "{{request_content}}"
    }
   ]
  },
  {
   "title": "Erroneous Calls rate Top10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(request_content) (increase(kindling_entity_request_total{namespace=\"$namespace\",workload_name=\"$workload\",protocol=\"$protocol\", response_content=~\"4..|5..|1|2|3\"}[$__interval])) / sum by(request_content) (increase(kindling_entity_request_total{namespace=\"$namespace\",workload_name=\"$workload\",protocol=\"$protocol\"}[$__interval])) * 100)",
     "legendFormat": "{{ request_content }}"
    }
   ]
  },
  {
   "title": "Request Detail",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "kindling_trace_request_duration_nanoseconds{is_server=\"true\", dst_namespace=\"$namespace\", dst_workload_name=\"$workload\", protocol=\"$protocol\"}[$__range]"
    }
   ]
  },
  { "title": "Upstream Performance ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Request Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kindling_topology_request_total{src_namespace=\"$namespace\",src_workload_name=\"$workload\",protocol=\"$protocol\"}[$__interval]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum by(src_namespace, src_workload_name) (increase(kindling_topology_request_duration_nanoseconds_total{src_namespace=\"$namespace\", src_workload_name=\"$workload\",protocol=\"$protocol\"}[$__interval])) / sum by(src_namespace, src_workload_name) \n (increase(kindling_topology_request_total{src_namespace=\"$namespace\", src_workload_name=\"$workload\",protocol=\"$protocol\"}[$__interval]))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Erroneous Calls rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (increase(kindling_topology_request_total{src_namespace=\"$namespace\",src_workload_name=\"$workload\",protocol=\"$protocol\",status_code=~\"4..|5..|1|2|3\"}[$__interval])) / sum (increase(kindling_topology_request_total{src_namespace=\"$namespace\",src_workload_name=\"$workload\",protocol=\"$protocol\"}[$__interval])) * 100"
    }
   ]
  },
  {
   "title": "Request Detail",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "kindling_trace_request_duration_nanoseconds{is_server=\"false\", src_namespace=\"$namespace\", src_workload_name=\"$workload\", protocol=\"$protocol\"}[$__range]"
    }
   ]
  }
 ]
}