name: Builder

on:
  push:
    paths:
      - "builder/**"
    branches:
      - master
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push Node
        run: cd ./builder/node && bash run.sh
      - name: Build and Push Golang
        run: cd ./builder/golang && bash run.sh
      - name: Build and Push Python
        run: cd ./builder/python && bash run.sh
      - name: Build and Push PyPy
        run: cd ./builder/pypy && bash run.sh
      - name: Build and Push Maven
        run: cd ./builder/maven && bash run.sh
