name: Builder

on:
  workflow_dispatch:
    inputs:
      builder:
        description: "选择要构建的构建器类型"
        required: true
        default: "ubuntu"
        type: choice
        options:
          - node
          - golang
          - python
          - pypy
          - maven

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push Node
        run: cd ./builder/${{ github.event.inputs.builder }} && bash run.sh
