name: docker-cli

on:
  push:
    paths:
      - "docker/cli/**"
    branches:
      - master
  workflow_dispatch:
jobs:
  docker-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push huggingface-cli
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: docker/cli/Dockerfile.huggingface-cli
          tags: shaowenchen/huggingface-cli:latest
      - name: Build and push git
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: docker/cli/Dockerfile.git
          tags: shaowenchen/git:latest
