name: RunShell

on:
  push:
    paths:
      - test/run.sh
  workflow_dispatch:
    inputs:
      path:
        description: "选择要运行的脚本"
        required: true
        default: './test/run.sh'
jobs:
  build:
    name: Run Shell Script
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Working
        run: |
          echo "Running script at ${{ inputs.path }}"
          chmod +x ${{ inputs.path }}
          cd $(dirname ${{ inputs.path }})
          bash $(basename ${{ inputs.path }})