name: Runtime

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: "选择要构建的运行时镜像"
        required: true
        default: "ubuntu"
        type: choice
        options:
          - ubuntu
          - python
          - pypy
          - openresty
          - nginx
          - openjdk
          - node

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push ${{ github.event.inputs.runtime }}
        run: cd ./runtime/${{ github.event.inputs.runtime }} && bash run.sh
